platform :ios, '8.0'
platform :ios, '7.0'
pod 'SDWebImage', '~>3.8'
pod 'YYKit'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'JSONModel'
pod 'MJExtension'
pod 'MJRefresh'
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
pod 'MWPhotoBrowser'
target 'XQQWeiboProj' do
pod 'AFNetworking', '~> 3.0'
end
